# Generated by Django 4.1.5 on 2023-01-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
