# Generated by Django 4.1.5 on 2023-01-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0002_remove_userinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
