# Generated by Django 4.1.5 on 2023-01-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0003_fileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='cont',
            field=models.CharField(default='abc', max_length=10000),
        ),
    ]
