# Generated by Django 4.1.5 on 2023-01-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0004_fileinfo_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='err',
            field=models.CharField(default='abc', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='cont',
            field=models.CharField(default='abc', max_length=1000),
        ),
    ]
