# Generated by Django 4.1.5 on 2023-01-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0006_fileinfo_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='val',
        ),
    ]
