# Generated by Django 4.1.5 on 2023-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0007_remove_fileinfo_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inval', models.CharField(default='abc', max_length=1000)),
                ('ouval', models.CharField(default='abc', max_length=1000)),
                ('err', models.CharField(default='abc', max_length=1000)),
            ],
        ),
    ]
