# Generated by Django 4.1.5 on 2023-01-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0008_resultinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='cont',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='err',
        ),
    ]
