# Generated by Django 4.1.5 on 2023-01-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0009_remove_fileinfo_cont_remove_fileinfo_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='cont',
            field=models.CharField(default='abc', max_length=10000),
        ),
    ]
