# Generated by Django 4.1.5 on 2023-01-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electron', '0011_resultinfo_result_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='cont',
        ),
    ]
